services:
  - type: web
    name: librarian-web
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run db:generate && npm run db:push && npm run db:seed && npm run build
    startCommand: npm run start --workspace=@librarian/web
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: librarian-postgres
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: librarian-postgres
          property: connectionString
      - key: AUTH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MEGA_FOLDER_URL
        value: https://mega.nz/folder/qNIjgLSB#NduwPvQZ4JlvEl-fIjZbkA

databases:
  - name: librarian-postgres
    plan: free
    region: frankfurt
    databaseName: librarian_db
    user: librarian
