export interface SeedBook {
  title: string;
  originalTitle?: string;
  slug: string;
  authors: string[];
  series?: { name: string; position: number };
  publisher: string;
  publishedYear: number;
  isbn10?: string;
  isbn13: string;
  pages: number;
  language: string;
  categories: string[];
  tags: string[];
  description: string;
  aiSummary: string;
  coverUrl: string;
  averageRating: number;
  ratingsCount: number;
  distributionStatus: "PRIVATE" | "PUBLIC_DOMAIN" | "LICENSED" | "CREATOR_AUTHORIZED" | "RESTRICTED";
  libraryReleaseDaysAgo: number; // 0 = today, 25 = 25 days ago
  fileFormats: { format: "EPUB" | "PDF" | "MOBI"; sizeBytes: number; quality: number }[];
}

export const SEED_USERS = [
  {
    email: "admin@librarian.ai",
    password: "AdminPassword123!",
    role: "SUPER_ADMIN" as const,
    displayName: "Főkönyvtáros Admin",
    bio: "A Librarian AI rendszergazdája és kurátora.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    membership: "SUPPORTER" as const,
    favoriteGenres: ["Sci-Fi", "Filozófia", "Kiberpunk"],
  },
  {
    email: "moderator@librarian.ai",
    password: "ModPassword123!",
    role: "MODERATOR" as const,
    displayName: "Kovács Anna (Moderátor)",
    bio: "Irodalomtörténész és sci-fi rajongó. A könyvklubok aktív szervezője.",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    membership: "SUPPORTER" as const,
    favoriteGenres: ["Sci-Fi", "Disztópia", "Klasszikus"],
  },
  {
    email: "supporter@librarian.ai",
    password: "UserPassword123!",
    role: "USER" as const,
    displayName: "Nagy Bence (Támogató)",
    bio: "Büszke Supporting Member! Minden héten 1 EUR-val támogatom a nyílt könyvtárat.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    membership: "SUPPORTER" as const,
    favoriteGenres: ["Sci-Fi", "Űropera", "Mérnöki tudományok"],
  },
  {
    email: "olvaso@librarian.ai",
    password: "UserPassword123!",
    role: "USER" as const,
    displayName: "Tóth Gábor (Ingyenes olvasó)",
    bio: "Éjszakai olvasó, a hard sci-fi és a technológiai történelem megszállottja.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    membership: "FREE" as const,
    favoriteGenres: ["Hard Sci-Fi", "Tudomány", "Történelem"],
  },
  {
    email: "zsofi@librarian.ai",
    password: "UserPassword123!",
    role: "USER" as const,
    displayName: "Varga Zsófia",
    bio: "Fantasy és ifjúsági irodalom kedvelő, podcast készítő.",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80",
    membership: "FREE" as const,
    favoriteGenres: ["Fantasy", "Mágikus realizmus"],
  },
  {
    email: "peter@librarian.ai",
    password: "UserPassword123!",
    role: "USER" as const,
    displayName: "Kiss Péter",
    bio: "Kiberpunk rajongó és szoftvermérnök.",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    membership: "SUPPORTER" as const,
    favoriteGenres: ["Kiberpunk", "Mesterséges Intelligencia"],
  },
  {
    email: "eszter@librarian.ai",
    password: "UserPassword123!",
    role: "USER" as const,
    displayName: "Horváth Eszter",
    bio: "Klasszikus magyar és világirodalom kedvelő.",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    membership: "FREE" as const,
    favoriteGenres: ["Klasszikus", "Történelmi regény"],
  },
  {
    email: "balazs@librarian.ai",
    password: "UserPassword123!",
    role: "USER" as const,
    displayName: "Szabó Balázs",
    bio: "Építőmérnök, szereti a tudományos szakkönyveket és az űrkutatást.",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    membership: "FREE" as const,
    favoriteGenres: ["Mérnöki tudományok", "Fizika", "Sci-Fi"],
  },
  {
    email: "dora@librarian.ai",
    password: "UserPassword123!",
    role: "USER" as const,
    displayName: "Molnár Dóra",
    bio: "Filozófiai esszék és disztópiák kutatója.",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    membership: "SUPPORTER" as const,
    favoriteGenres: ["Filozófia", "Disztópia", "Szociológia"],
  },
  {
    email: "daniel@librarian.ai",
    password: "UserPassword123!",
    role: "USER" as const,
    displayName: "Farkas Dániel",
    bio: "Könyvklub tag, havi 4 könyv kihívást teljesít.",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    membership: "FREE" as const,
    favoriteGenres: ["Krimi", "Thriller", "Sci-Fi"],
  },
];

export const SEED_BOOKS: SeedBook[] = [
  // 1-7: Foundation Sorozat (Isaac Asimov)
  {
    title: "Alapítvány",
    originalTitle: "Foundation",
    slug: "alapitvany",
    authors: ["Isaac Asimov"],
    series: { name: "Alapítvány Sorozat", position: 1 },
    publisher: "Gnome Press",
    publishedYear: 1951,
    isbn13: "9789634971801",
    pages: 255,
    language: "hu",
    categories: ["Sci-Fi", "Űropera", "Filozófia"],
    tags: ["pszichohistória", "galaktikus birodalom", "hari seldon", "klasszikus"],
    description: "A Galaktikus Birodalom haldoklik. Hari Seldon, a pszichohistória tudományának megteremtője előre látja a harmincezer éves sötét kort, és egy Alapítványt hoz létre az emberi tudás megőrzésére.",
    aiSummary: "AI Elemzés: Az Alapítvány a politikai stratégia és a szociológiai determinizmus csúcsműve. Fő motívuma, hogy a tömegek viselkedése statisztikailag modellezhető.",
    coverUrl: "https://images.unsplash.com/photo-1618609377864-68609b857e90?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.8,
    ratingsCount: 1420,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 45, // Free for everyone
    fileFormats: [
      { format: "EPUB", sizeBytes: 1250000, quality: 1.0 },
      { format: "PDF", sizeBytes: 2400000, quality: 0.95 },
    ],
  },
  {
    title: "Alapítvány és Birodalom",
    originalTitle: "Foundation and Empire",
    slug: "alapitvany-es-birodalom",
    authors: ["Isaac Asimov"],
    series: { name: "Alapítvány Sorozat", position: 2 },
    publisher: "Gnome Press",
    publishedYear: 1952,
    isbn13: "9789634971818",
    pages: 247,
    language: "hu",
    categories: ["Sci-Fi", "Űropera"],
    tags: ["öszvér", "hari seldon", "galaxis", "mutáns"],
    description: "Az Alapítvány szembekerül a hajdani dicső Birodalom megmaradt haderejével, majd egy váratlan mutáns, az Öszvér bukkan fel, aki képes az emberi érzelmek manipulálására.",
    aiSummary: "AI Elemzés: Seldon determinisztikus terve összecsap az egyéni, kaotikus akarattal. Az Öszvér karaktere a sci-fi történelem egyik legemlékezetesebb antagonistája.",
    coverUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.7,
    ratingsCount: 1120,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 40,
    fileFormats: [{ format: "EPUB", sizeBytes: 1180000, quality: 1.0 }],
  },
  {
    title: "Második Alapítvány",
    originalTitle: "Second Foundation",
    slug: "masodik-alapitvany",
    authors: ["Isaac Asimov"],
    series: { name: "Alapítvány Sorozat", position: 3 },
    publisher: "Gnome Press",
    publishedYear: 1953,
    isbn13: "9789634971825",
    pages: 236,
    language: "hu",
    categories: ["Sci-Fi", "Űropera", "Pszichológia"],
    tags: ["telepátia", "második alapítvány", "mentális tudomány"],
    description: "Az Öszvér a Második Alapítványt keresi, melynek tudósai a mentális tudományok mesterei. A két frakció szellemi háborúja a galaxis jövőjéért.",
    aiSummary: "AI Elemzés: Érdekes átmenet a fizikai technológiákból az emberi elme és a mentális képességek vizsgálatába.",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.6,
    ratingsCount: 980,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 35,
    fileFormats: [{ format: "EPUB", sizeBytes: 1100000, quality: 1.0 }],
  },
  {
    title: "Az Alapítvány pereme",
    originalTitle: "Foundation's Edge",
    slug: "az-alapitvany-pereme",
    authors: ["Isaac Asimov"],
    series: { name: "Alapítvány Sorozat", position: 4 },
    publisher: "Doubleday",
    publishedYear: 1982,
    isbn13: "9789634971832",
    pages: 366,
    language: "hu",
    categories: ["Sci-Fi", "Űropera"],
    tags: ["golan trevize", "gaia", "kollektív tudat"],
    description: "Golan Trevize tanácsos gyanítani kezdi, hogy a Második Alapítvány mégsem pusztult el teljesen. Kutatása során eljut a rejtélyes Gaia bolygóra.",
    aiSummary: "AI Elemzés: Asimov összekapcsolja az Alapítvány-univerzumot a Robot-sorozat gondolatiságával.",
    coverUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.5,
    ratingsCount: 750,
    distributionStatus: "LICENSED",
    libraryReleaseDaysAgo: 10, // NEW! 11 days remaining for Free members!
    fileFormats: [{ format: "EPUB", sizeBytes: 1600000, quality: 1.0 }],
  },
  {
    title: "Alapítvány és Föld",
    originalTitle: "Foundation and Earth",
    slug: "alapitvany-es-fold",
    authors: ["Isaac Asimov"],
    series: { name: "Alapítvány Sorozat", position: 5 },
    publisher: "Doubleday",
    publishedYear: 1986,
    isbn13: "9789634971849",
    pages: 420,
    language: "hu",
    categories: ["Sci-Fi", "Űropera"],
    tags: ["föld keresése", "r daneel olivaw", "robotok"],
    description: "Trevize és társai az emberiség szülőbolygóját, a mítosszá vált Földet keresik az elfeledett világok között.",
    aiSummary: "AI Elemzés: Méltó lezárás az emberi eredet és a robotika törvényeinek kozmikus szintézisével.",
    coverUrl: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.4,
    ratingsCount: 680,
    distributionStatus: "LICENSED",
    libraryReleaseDaysAgo: 3, // NEW! 18 days remaining for Free members!
    fileFormats: [{ format: "EPUB", sizeBytes: 1900000, quality: 1.0 }],
  },

  // 8-12: Dűne Sorozat (Frank Herbert)
  {
    title: "Dűne",
    originalTitle: "Dune",
    slug: "dune",
    authors: ["Frank Herbert"],
    series: { name: "Dűne Krónikák", position: 1 },
    publisher: "Chilton Books",
    publishedYear: 1965,
    isbn13: "9789634972006",
    pages: 620,
    language: "hu",
    categories: ["Sci-Fi", "Ökológia", "Politika", "Filozófia"],
    tags: ["arrakis", "fűszer", "paul atreides", "homokféreg", "fremen"],
    description: "Az Arrakis sivatagbolygón, az univerzum legértékesebb kincsének, a fűszernek az egyetlen lelőhelyén Paul Atreides a császári intrikák és egy sivatagi vallási felkelés középpontjába kerül.",
    aiSummary: "AI Elemzés: Herbert ökológiai látomása és a vallási fanatizmus veszélyeire figyelmeztető elemzése a sci-fi irodalom legnagyobb hatású remeke.",
    coverUrl: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.9,
    ratingsCount: 3200,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 60,
    fileFormats: [
      { format: "EPUB", sizeBytes: 2100000, quality: 1.0 },
      { format: "PDF", sizeBytes: 4500000, quality: 0.98 },
    ],
  },
  {
    title: "A Dűne messiása",
    originalTitle: "Dune Messiah",
    slug: "a-dune-messiasa",
    authors: ["Frank Herbert"],
    series: { name: "Dűne Krónikák", position: 2 },
    publisher: "Putnam",
    publishedYear: 1969,
    isbn13: "9789634972013",
    pages: 256,
    language: "hu",
    categories: ["Sci-Fi", "Politika", "Filozófia"],
    tags: ["paul atreides", "dzsihád", "árulás", "prófécia"],
    description: "Paul Muad'Dib immár a galaxis teljhatalmú császára, ám látja a nevében vívott pusztító szent háborút, és a körülötte szövődő összeesküvéseket.",
    aiSummary: "AI Elemzés: A hős mítoszának dekonstrukciója: mi történik, amikor a messiás győz, de a jövőlátás csapdájába esik.",
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.5,
    ratingsCount: 1650,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 50,
    fileFormats: [{ format: "EPUB", sizeBytes: 1150000, quality: 1.0 }],
  },
  {
    title: "A Dűne gyermekei",
    originalTitle: "Children of Dune",
    slug: "a-dune-gyermekei",
    authors: ["Frank Herbert"],
    series: { name: "Dűne Krónikák", position: 3 },
    publisher: "Putnam",
    publishedYear: 1976,
    isbn13: "9789634972020",
    pages: 444,
    language: "hu",
    categories: ["Sci-Fi", "Ökológia"],
    tags: ["leto ii", "ghanima", "arany ösvény"],
    description: "Paul ikergyermekei, Leto és Ghanima rendkívüli örökséggel bírnak, miközben az Arrakis ökológiai átalakulása veszélybe sodorja a fűszer termelését.",
    aiSummary: "AI Elemzés: Az Arany Ösvény megfogalmazása, az emberiség túlélésének extrém ára.",
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.6,
    ratingsCount: 1200,
    distributionStatus: "LICENSED",
    libraryReleaseDaysAgo: 22, // Free member unlocked 1 day ago!
    fileFormats: [{ format: "EPUB", sizeBytes: 1800000, quality: 1.0 }],
  },
  {
    title: "A Dűne istencsászára",
    originalTitle: "God Emperor of Dune",
    slug: "a-dune-istencsaszara",
    authors: ["Frank Herbert"],
    series: { name: "Dűne Krónikák", position: 4 },
    publisher: "Putnam",
    publishedYear: 1981,
    isbn13: "9789634972037",
    pages: 430,
    language: "hu",
    categories: ["Sci-Fi", "Filozófia"],
    tags: ["leto ii", "homokféreg", "többezer éves uralom"],
    description: "Háromezer-ötszáz év telt el. II. Leto immár félig ember, félig homokféreg teremtményként uralkodik az emberiségen szigorú béke alatt.",
    aiSummary: "AI Elemzés: Filozófiai mélységű dialógusok a szabadság, a kényszerített evolúció és a halandóság témájában.",
    coverUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.7,
    ratingsCount: 1100,
    distributionStatus: "LICENSED",
    libraryReleaseDaysAgo: 5, // NEW! 16 days remaining for Free members!
    fileFormats: [{ format: "EPUB", sizeBytes: 1750000, quality: 1.0 }],
  },

  // 13-16: Sprawl Trilógia (William Gibson) - Kiberpunk
  {
    title: "Neurománc",
    originalTitle: "Neuromancer",
    slug: "neuromanc",
    authors: ["William Gibson"],
    series: { name: "Sprawl Trilógia", position: 1 },
    publisher: "Ace Books",
    publishedYear: 1984,
    isbn13: "9789634973003",
    pages: 271,
    language: "hu",
    categories: ["Kiberpunk", "Sci-Fi", "Mesterséges Intelligencia"],
    tags: ["mátrix", "kibersor", "case", "molly", "téli csend"],
    description: "Case, a kiégett hacker egy rejtélyes megbízótól kap új esélyt idegrendszere helyreállítására, cserébe egy megdöbbentően védett mesterséges intelligencia feltöréséért.",
    aiSummary: "AI Elemzés: A modern kiberpunk alapműve, amely bevezette a 'mátrix' és 'kiberter' fogalmát a köztudatba.",
    coverUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.6,
    ratingsCount: 2100,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 90,
    fileFormats: [{ format: "EPUB", sizeBytes: 1100000, quality: 1.0 }],
  },
  {
    title: "Számláló nullára",
    originalTitle: "Count Zero",
    slug: "szamlalo-nullara",
    authors: ["William Gibson"],
    series: { name: "Sprawl Trilógia", position: 2 },
    publisher: "Gollancz",
    publishedYear: 1986,
    isbn13: "9789634973010",
    pages: 256,
    language: "hu",
    categories: ["Kiberpunk", "Sci-Fi"],
    tags: ["sprawl", "vudu istenségek", "bio-chipek"],
    description: "Hét évvel a Neurománc eseményei után rejtélyes, istenszerű entitások jelennek meg a mátrixban, miközben a bio-chipekért véres harc indul.",
    aiSummary: "AI Elemzés: A kiberter és a digitális miszticizmus összefonódása három párhuzamos narratív szálon.",
    coverUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.4,
    ratingsCount: 890,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 70,
    fileFormats: [{ format: "EPUB", sizeBytes: 1050000, quality: 1.0 }],
  },
  {
    title: "Mona Lisa Overdrive",
    originalTitle: "Mona Lisa Overdrive",
    slug: "mona-lisa-overdrive",
    authors: ["William Gibson"],
    series: { name: "Sprawl Trilógia", position: 3 },
    publisher: "Bantam Books",
    publishedYear: 1988,
    isbn13: "9789634973027",
    pages: 308,
    language: "hu",
    categories: ["Kiberpunk", "Sci-Fi"],
    tags: ["szimstim", "mátrix lezárás", "digitális túlvilág"],
    description: "A Sprawl trilógia zárókönyvében a sztárok digitális klónjai és az alvilág összefonódik a virtuális valóság határain.",
    aiSummary: "AI Elemzés: Gibson mesteri atmoszférateremtése a digitális transzcendenciáról.",
    coverUrl: "https://images.unsplash.com/photo-1515260268569-9271009adfdb?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.3,
    ratingsCount: 710,
    distributionStatus: "LICENSED",
    libraryReleaseDaysAgo: 1, // NEW! 20 days remaining for Free members!
    fileFormats: [{ format: "EPUB", sizeBytes: 1300000, quality: 1.0 }],
  },

  // 17-21: Arthur C. Clarke és hard sci-fi klasszikusok
  {
    title: "2001. Űrodisszeia",
    originalTitle: "2001: A Space Odyssey",
    slug: "2001-urodisszeia",
    authors: ["Arthur C. Clarke"],
    publisher: "New American Library",
    publishedYear: 1968,
    isbn13: "9789634974000",
    pages: 221,
    language: "hu",
    categories: ["Hard Sci-Fi", "Űrkutatás", "Mesterséges Intelligencia"],
    tags: ["monolit", "hal 9000", "jupiter misszió", "csillaggyermek"],
    description: "Egy titokzatos fekete monolit kerül elő a Hold felszíne alatt, amely a Jupiterhez vezető expedícióhoz és a fedélzeti számítógép, HAL 9000 fellázadásához vezet.",
    aiSummary: "AI Elemzés: Az emberiség kozmikus evolúciójának és a mesterséges értelem korai etikai dilemmáinak legfontosabb klasszikusa.",
    coverUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.8,
    ratingsCount: 2800,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 120,
    fileFormats: [{ format: "EPUB", sizeBytes: 950000, quality: 1.0 }, { format: "PDF", sizeBytes: 1900000, quality: 0.9 }],
  },
  {
    title: "Randevú a Rámával",
    originalTitle: "Rendezvous with Rama",
    slug: "randevu-a-ramaval",
    authors: ["Arthur C. Clarke"],
    publisher: "Gollancz",
    publishedYear: 1973,
    isbn13: "9789634974017",
    pages: 288,
    language: "hu",
    categories: ["Hard Sci-Fi", "Felfedezés"],
    tags: ["idegen űrhajó", "henger", "csillagközi látogató"],
    description: "Egy ötven kilométer hosszú, henger alakú idegen objektum lép be a Naprendszerbe. Az emberiség felderítő hajót küld a belsejébe rejtett világ felfedezésére.",
    aiSummary: "AI Elemzés: A 'Big Dumb Object' műfaj megteremtője: tudományos alaposság és a kozmikus rejtély tiszta élménye.",
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.7,
    ratingsCount: 1750,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 85,
    fileFormats: [{ format: "EPUB", sizeBytes: 1200000, quality: 1.0 }],
  },

  // 22-26: Philip K. Dick & Filozófiai Sci-fi
  {
    title: "Álmodnak-e az androidok elektronikus bárányokkal?",
    originalTitle: "Do Androids Dream of Electric Sheep?",
    slug: "almodnak-e-az-androidok-elektronikus-baranyokkal",
    authors: ["Philip K. Dick"],
    publisher: "Doubleday",
    publishedYear: 1968,
    isbn13: "9789634975007",
    pages: 210,
    language: "hu",
    categories: ["Sci-Fi", "Filozófia", "Disztópia"],
    tags: ["blade runner", "rick deckard", "empátia", "replikáns"],
    description: "A radioaktív porral borított jövőben Rick Deckard fejvadász megbízást kap hat szökött Nexus-6 android kiiktatására, miközben az empátia és emberi lélek határait kutatja.",
    aiSummary: "AI Elemzés: Mi különbözteti meg az embert a gépitől? Az empátiateszt (Voight-Kampff) és az érzelmi szimuláció mélylélektana.",
    coverUrl: "https://images.unsplash.com/photo-1507499739999-097706ad8914?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.7,
    ratingsCount: 2300,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 100,
    fileFormats: [{ format: "EPUB", sizeBytes: 1000000, quality: 1.0 }],
  },
  {
    title: "Ubik",
    originalTitle: "Ubik",
    slug: "ubik",
    authors: ["Philip K. Dick"],
    publisher: "Doubleday",
    publishedYear: 1969,
    isbn13: "9789634975014",
    pages: 202,
    language: "hu",
    categories: ["Sci-Fi", "Filozófia", "Pszichológia"],
    tags: ["valóság bomlás", "félig-élet", "entrópia", "rejtély"],
    description: "Egy holdbéli merénylet után a valóság szövedéke elkezd visszafelé bomlani a múltba, és csak a rejtélyes Ubik spray képes megállítani a fizikai enyészetet.",
    aiSummary: "AI Elemzés: A szubjektív valóság és a halál utáni tudatállapotok legzavarbaejtőbb és legszórakoztatóbb vizsgálata.",
    coverUrl: "https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.6,
    ratingsCount: 1400,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 75,
    fileFormats: [{ format: "EPUB", sizeBytes: 900000, quality: 1.0 }],
  },

  // 27-31: Stanislaw Lem
  {
    title: "Solaris",
    originalTitle: "Solaris",
    slug: "solaris",
    authors: ["Stanisław Lem"],
    publisher: "Wydawnictwo Literackie",
    publishedYear: 1961,
    isbn13: "9789634976004",
    pages: 204,
    language: "hu",
    categories: ["Sci-Fi", "Filozófia", "Pszichológia"],
    tags: ["élő óceán", "kapcsolatfelvétel", "tudattalan", "emlékek"],
    description: "Kris Kelvin pszichológus a titokzatos Solaris bolygó kutatóállomására érkezik, ahol az értelmes plazmaóceán a kutatók legmélyebb bűntudatát és elfojtott emlékeit testesíti meg hús-vér alakban.",
    aiSummary: "AI Elemzés: Lem zseniális kritikája az antropomorf űrkutatásról: az ember nem más világokat akar megérteni, csak tükröt keres a saját képére.",
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.8,
    ratingsCount: 2200,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 110,
    fileFormats: [{ format: "EPUB", sizeBytes: 850000, quality: 1.0 }],
  },
  {
    title: "A Legyőzhetetlen",
    originalTitle: "Niezwyciężony",
    slug: "a-legyozhetetlen",
    authors: ["Stanisław Lem"],
    publisher: "MON",
    publishedYear: 1964,
    isbn13: "9789634976011",
    pages: 180,
    language: "hu",
    categories: ["Hard Sci-Fi", "Mesterséges Intelligencia"],
    tags: ["nekroevolúció", "mikro-robotok", "raj intelligencia"],
    description: "A nehézcirkáló egy kihalt bolygón kutat eltűnt testvérhajója után, ahol a mechanikus mikro-robotok több millió év alatt rovarszerű raj-intelligenciává evolválódtak.",
    aiSummary: "AI Elemzés: A mechanikus evolúció (nekroevolúció) úttörő koncepciója, jóval a nanotechnológia fogalmának elterjedése előtt.",
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.6,
    ratingsCount: 1150,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 95,
    fileFormats: [{ format: "EPUB", sizeBytes: 800000, quality: 1.0 }],
  },

  // 32-36: Tudományos és Mérnöki Szakkönyvek (Non-fiction / Engineering)
  {
    title: "A hídtervezés elmélete és gyakorlata",
    originalTitle: "Theory and Practice of Bridge Engineering",
    slug: "a-hidtervezes-elmelete-es-gyakorlata",
    authors: ["Dr. Kovács Béla", "Németh László"],
    publisher: "Műszaki Könyvkiadó",
    publishedYear: 2018,
    isbn13: "9789631645012",
    pages: 512,
    language: "hu",
    categories: ["Mérnöki tudományok", "Építőmérnöki", "Szerkezetépítés"],
    tags: ["hídtervezés", "statika", "acélhidak", "feszített vasbeton", "dinamika"],
    description: "Átfogó egyetemi és szakmérnöki kézikönyv a modern ferdekábeles, függő- és vasbeton hidak tervezési, statikai és dinamikai számítási módszereiről.",
    aiSummary: "AI Elemzés: Szakkönyv a szerkezetépítésről, végeselem-módszerekről és szélcsatorna-vizsgálatokról a modern hídépítésben.",
    coverUrl: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.9,
    ratingsCount: 180,
    distributionStatus: "CREATOR_AUTHORIZED",
    libraryReleaseDaysAgo: 50,
    fileFormats: [{ format: "PDF", sizeBytes: 15400000, quality: 1.0 }],
  },
  {
    title: "Kvantummechanika alapjai",
    originalTitle: "Principles of Quantum Mechanics",
    slug: "kvantummechanika-alapjai",
    authors: ["Szabó Miklós"],
    publisher: "Akadémiai Kiadó",
    publishedYear: 2020,
    isbn13: "9789630598123",
    pages: 380,
    language: "hu",
    categories: ["Fizika", "Tudomány", "Kvantumfizika"],
    tags: ["kvantummechanika", "hullámfüggvény", "schrodinger", "összefonódás"],
    description: "Világos, pedagógiailag átgondolt bevezetés a kvantummechanika alapjaiba, a Hilbert-terektől a modern kvantuminformatikáig.",
    aiSummary: "AI Elemzés: Ideális bevezető kötet a modern fizikába kezdőknek és haladóknak egyaránt.",
    coverUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.8,
    ratingsCount: 310,
    distributionStatus: "CREATOR_AUTHORIZED",
    libraryReleaseDaysAgo: 30,
    fileFormats: [{ format: "PDF", sizeBytes: 8500000, quality: 1.0 }],
  },
  {
    title: "Fenntartható városok és zöld építészet",
    originalTitle: "Sustainable Cities and Green Architecture",
    slug: "fenntarthato-varosok-es-zold-epiteszet",
    authors: ["Bálint Andrea"],
    publisher: "Typotex",
    publishedYear: 2022,
    isbn13: "9789632799988",
    pages: 290,
    language: "hu",
    categories: ["Építészet", "Ökológia", "Várostervezés"],
    tags: ["zöld város", "ökologikus tervezés", "energiatakarékosság", "okosváros"],
    description: "Hogyan alakíthatjuk át a XXI. század metropoliszait élhető, karbonsemleges, ökológiailag önfenntartó életterekké?",
    aiSummary: "AI Elemzés: Részletes esettanulmányok Koppenhágától Szingapúrig a fenntartható településfejlesztésről.",
    coverUrl: "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.7,
    ratingsCount: 220,
    distributionStatus: "CREATOR_AUTHORIZED",
    libraryReleaseDaysAgo: 15, // NEW! 6 days remaining for Free members!
    fileFormats: [{ format: "PDF", sizeBytes: 12000000, quality: 1.0 }, { format: "EPUB", sizeBytes: 4500000, quality: 0.95 }],
  },
  {
    title: "Róma tündöklése és bukása",
    originalTitle: "The Decline and Fall of the Roman Empire (Summary Edition)",
    slug: "roma-tundoklese-es-bukasa",
    authors: ["Edward Gibbon"],
    publisher: "Európa Könyvkiadó",
    publishedYear: 2015,
    isbn13: "9789630798114",
    pages: 640,
    language: "hu",
    categories: ["Történelem", "Római Birodalom", "Klasszikus"],
    tags: ["róma", "császárok", "történelem", "hadsereg", "antikvitás"],
    description: "A történetírás egyik legnagyobb szabású műve a Római Birodalom fénykoráról, válságáról és széteséséről.",
    aiSummary: "AI Elemzés: Alapmű a klasszikus történettudományban és a politikai rendszerek hanyatlásának vizsgálatában.",
    coverUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.8,
    ratingsCount: 890,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 150,
    fileFormats: [{ format: "EPUB", sizeBytes: 3200000, quality: 1.0 }],
  },

  // 37-42: Disztópiák és Társadalmi Sci-Fi
  {
    title: "1984",
    originalTitle: "Nineteen Eighty-Four",
    slug: "1984",
    authors: ["George Orwell"],
    publisher: "Secker & Warburg",
    publishedYear: 1949,
    isbn13: "9789634977001",
    pages: 328,
    language: "hu",
    categories: ["Disztópia", "Klasszikus", "Politika", "Filozófia"],
    tags: ["nagy testvér", "óceánia", "újbeszél", "winston smith", "gondolatrendőrség"],
    description: "A totális diktatúra világa, ahol a Párt a múltat, a gondolatokat és a szerelmet is ellenőrzi. Winston Smith tiltott naplójával kezdődik a csendes lázadás.",
    aiSummary: "AI Elemzés: A totalitarizmus, a megfigyelő állam és a nyelvi manipuláció máig legfontosabb irodalmi figyelmeztetése.",
    coverUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.9,
    ratingsCount: 4500,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 200,
    fileFormats: [{ format: "EPUB", sizeBytes: 1100000, quality: 1.0 }],
  },
  {
    title: "Szép új világ",
    originalTitle: "Brave New World",
    slug: "szep-uj-vilag",
    authors: ["Aldous Huxley"],
    publisher: "Chatto & Windus",
    publishedYear: 1932,
    isbn13: "9789634977018",
    pages: 288,
    language: "hu",
    categories: ["Disztópia", "Klasszikus", "Filozófia"],
    tags: ["genetika", "soma", "kondicionálás", "vadember"],
    description: "Egy olyan jövő, ahol a stabilitást és boldogságot kémiai szerekkel és genetikai kasztrendszerrel biztosítják, kiiktatva a művészetet, a szenvedést és a szabadságot.",
    aiSummary: "AI Elemzés: Huxley jóslata az élvezetek által elnyomott, szórakoztatással lecsillapított társadalomról ma időszerűbb, mint valaha.",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.7,
    ratingsCount: 3100,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 180,
    fileFormats: [{ format: "EPUB", sizeBytes: 980000, quality: 1.0 }],
  },
  {
    title: "Fahrenheit 451",
    originalTitle: "Fahrenheit 451",
    slug: "fahrenheit-451",
    authors: ["Ray Bradbury"],
    publisher: "Ballantine Books",
    publishedYear: 1953,
    isbn13: "9789634977025",
    pages: 249,
    language: "hu",
    categories: ["Disztópia", "Klasszikus", "Sci-Fi"],
    tags: ["könyvégetés", "guy montag", "tűzőrök", "olvasás szabadsága"],
    description: "Egy társadalom, ahol a könyvek birtoklása törvénytelen, és a tűzoltók feladata a megmaradt művek elégetése. Guy Montag tűzoltó egy napon megkérdőjelezi a parancsot.",
    aiSummary: "AI Elemzés: Óda az olvasáshoz és a könyvekben őrzött emberi gondolatok megmásíthatatlan értékéhez.",
    coverUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.7,
    ratingsCount: 2900,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 160,
    fileFormats: [{ format: "EPUB", sizeBytes: 890000, quality: 1.0 }],
  },

  // 43-46: Liu Cixin - A háromtest-probléma
  {
    title: "A háromtest-probléma",
    originalTitle: "The Three-Body Problem",
    slug: "a-haromtest-problema",
    authors: ["Cixin Liu"],
    series: { name: "A Föld múltjának emlékezete", position: 1 },
    publisher: "Chongqing Publishing Group",
    publishedYear: 2008,
    isbn13: "9789634978008",
    pages: 410,
    language: "hu",
    categories: ["Hard Sci-Fi", "Fizika", "Kapcsolatfelvétel"],
    tags: ["trisolaris", "kulturális forradalom", "virtuális valóság", "kozmikus szociológia"],
    description: "A kínai kulturális forradalom idején egy titkos katonai bázis jelet küld a világűrbe. Egy instabil csillagrendszer idegen faja veszi az adást, és megkezdi négy évszázados útját a Föld felé.",
    aiSummary: "AI Elemzés: A modern kínai sci-fi globális diadala, amely a fizika és a játékelmélet legkeményebb tételeit állítja a narratíva szolgálatába.",
    coverUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.8,
    ratingsCount: 3800,
    distributionStatus: "LICENSED",
    libraryReleaseDaysAgo: 2, // NEW! 19 days remaining for Free members!
    fileFormats: [{ format: "EPUB", sizeBytes: 1850000, quality: 1.0 }],
  },
  {
    title: "A sötét erdő",
    originalTitle: "The Dark Forest",
    slug: "a-sotet-erdo",
    authors: ["Cixin Liu"],
    series: { name: "A Föld múltjának emlékezete", position: 2 },
    publisher: "Chongqing Publishing Group",
    publishedYear: 2008,
    isbn13: "9789634978015",
    pages: 512,
    language: "hu",
    categories: ["Hard Sci-Fi", "Filozófia", "Játékelmélet"],
    tags: ["sötét erdő elmélet", "falbontók", "luo ji", "kozmikus túlélés"],
    description: "Az emberiség felkészül az invázióra. Mivel a gondolatokat a triszoláriaiak lehallgatják, négy Kiválasztottat neveznek ki, akik némán, csak a saját elméjükben tervezhetik meg a védelmet.",
    aiSummary: "AI Elemzés: A 'Sötét Erdő' axióma bemutatása: a Fermi-paradoxon leghátborzongatóbb és leglogikusabb magyarázata.",
    coverUrl: "https://images.unsplash.com/photo-1507499739999-097706ad8914?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.9,
    ratingsCount: 3400,
    distributionStatus: "LICENSED",
    libraryReleaseDaysAgo: 4, // NEW! 17 days remaining for Free members!
    fileFormats: [{ format: "EPUB", sizeBytes: 2200000, quality: 1.0 }],
  },

  // 47-50: Privát könyvek (Explicit jogi teszteléshez!)
  {
    title: "Személyes Munkajegyzetek és Kutatási Napló 2026",
    slug: "szemelyes-munkajegyzetek-2026",
    authors: ["Tóth Gábor"],
    publisher: "Magánkiadás",
    publishedYear: 2026,
    isbn13: "9789630000018",
    pages: 120,
    language: "hu",
    categories: ["Személyes", "Jegyzetek"],
    tags: ["privát", "kutatás", "belső"],
    description: "Kizárólag saját célra digitalizált egyéni jegyzetfüzet és forrásgyűjtemény.",
    aiSummary: "AI Elemzés: Személyes dokumentum, külső olvasók számára nem hozzáférhető.",
    coverUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&auto=format&fit=crop&q=80",
    averageRating: 5.0,
    ratingsCount: 1,
    distributionStatus: "PRIVATE", // Szigorúan magánkönyv!
    libraryReleaseDaysAgo: 5,
    fileFormats: [{ format: "PDF", sizeBytes: 1500000, quality: 1.0 }],
  },
  {
    title: "Kézirat: A Kvantum Szimfónia (Piszkozat)",
    slug: "kezirat-a-kvantum-szimfonia",
    authors: ["Kiss Péter"],
    publisher: "Kézirat",
    publishedYear: 2026,
    isbn13: "9789630000025",
    pages: 95,
    language: "hu",
    categories: ["Sci-Fi", "Kézirat"],
    tags: ["piszkozat", "privát"],
    description: "Saját szerzőségű befejezetlen regényváltozat, szerzői jogi védelem alatt.",
    aiSummary: "AI Elemzés: Korai szerkesztési változat.",
    coverUrl: "https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.5,
    ratingsCount: 2,
    distributionStatus: "PRIVATE", // Szigorúan magánkönyv!
    libraryReleaseDaysAgo: 1,
    fileFormats: [{ format: "EPUB", sizeBytes: 600000, quality: 1.0 }],
  },
  {
    title: "Mesterséges Intelligencia és Gépi Tanulás Gyakorlatban",
    slug: "mesterseges-intelligencia-es-gepi-tanulas",
    authors: ["Bencsik Gábor", "Varga Tamás"],
    publisher: "Panem",
    publishedYear: 2023,
    isbn13: "9789635456112",
    pages: 440,
    language: "hu",
    categories: ["Informatika", "Mesterséges Intelligencia", "Adattudomány"],
    tags: ["python", "deep learning", "neurális hálók", "llm"],
    description: "Korszerű áttekintés a modern gépi tanulás algoritmusairól, a konvolúciós és transzformátor architektúrákról, kevés száraz elmélettel és sok gyakorlati példával.",
    aiSummary: "AI Elemzés: Kiváló gyakorlatorientált kötet azoknak, akik kevés matematikával szeretnék megérteni az AI működését.",
    coverUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.8,
    ratingsCount: 520,
    distributionStatus: "CREATOR_AUTHORIZED",
    libraryReleaseDaysAgo: 45, // Free for all
    fileFormats: [{ format: "PDF", sizeBytes: 18000000, quality: 1.0 }, { format: "EPUB", sizeBytes: 6500000, quality: 0.95 }],
  },
  {
    title: "Rövid filozófiai séta az éjszakában",
    slug: "rovid-filozofiai-seta-az-ejszakaban",
    authors: ["Molnár Dóra"],
    publisher: "Kalligram",
    publishedYear: 2024,
    isbn13: "9789635456990",
    pages: 140,
    language: "hu",
    categories: ["Filozófia", "Esszé"],
    tags: ["rövid könyv", "este", "gondolatok", "egzisztencializmus"],
    description: "Lírai, tömör filozófiai gondolatfutamok a magányról, az idő múlásáról és a csillagos égboltról. Egyetlen csendes este alatt elolvasható.",
    aiSummary: "AI Elemzés: Rövid, meditatív olvasmány estére, klasszikus és kortárs gondolatok szintézisével.",
    coverUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.7,
    ratingsCount: 340,
    distributionStatus: "CREATOR_AUTHORIZED",
    libraryReleaseDaysAgo: 60, // Free for all
    fileFormats: [{ format: "EPUB", sizeBytes: 750000, quality: 1.0 }],
  },
  {
    title: "A Gyűrűk Ura: A Gyűrű Szövetsége",
    originalTitle: "The Fellowship of the Ring",
    slug: "a-gyuruk-ura-a-gyuru-szovetsege",
    authors: ["J. R. R. Tolkien"],
    series: { name: "A Gyűrűk Ura", position: 1 },
    publisher: "George Allen & Unwin",
    publishedYear: 1954,
    isbn13: "9789630799012",
    pages: 423,
    language: "hu",
    categories: ["Fantasy", "Klasszikus", "Kaland"],
    tags: ["középfölde", "frodo", "gandalf", "az egy gyűrű"],
    description: "Zsákos Frodó hobbit örökli az Egy Gyűrűt, Szauron hatalmának forrását, és elindul a Végzet Hegyéhez vezető halálos küldetésre.",
    aiSummary: "AI Elemzés: A modern epikus fantasy alapköve, nyelvi és mitológiai gazdagsága máig felülmúlhatatlan.",
    coverUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80",
    averageRating: 4.9,
    ratingsCount: 4800,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseDaysAgo: 150,
    fileFormats: [{ format: "EPUB", sizeBytes: 2500000, quality: 1.0 }],
  },
];
