import { BookItem } from "@librarian/ai";

export const FALLBACK_BOOKS: BookItem[] = [
  {
    id: "fb_asimov_1",
    title: "Alapítvány",
    slug: "alapitvany",
    description: "A Galaktikus Birodalom haldoklik. Hari Seldon pszichohistóriája alapján megalapítják az Alapítványt.",
    authors: [{ name: "Isaac Asimov" }],
    categories: [{ name: "Sci-Fi" }, { name: "Űropera" }],
    tags: [{ name: "klasszikus" }, { name: "pszichohistória" }],
    averageRating: 4.8,
    ratingsCount: 1420,
    coverUrl: "https://images.unsplash.com/photo-1618609377864-68609b857e90?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1951,
    pages: 255,
    seriesName: "Alapítvány",
    seriesPosition: 1,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_asimov_2",
    title: "Alapítvány és Birodalom",
    slug: "alapitvany-es-birodalom",
    description: "Az Alapítvány szembekerül a hajdani dicső Birodalommal és a titokzatos Öszvérrel.",
    authors: [{ name: "Isaac Asimov" }],
    categories: [{ name: "Sci-Fi" }, { name: "Űropera" }],
    tags: [{ name: "öszvér" }, { name: "galaxis" }],
    averageRating: 4.7,
    ratingsCount: 1120,
    coverUrl: "https://images.unsplash.com/photo-1532012164546-f432f2e3777f?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1952,
    pages: 247,
    seriesName: "Alapítvány",
    seriesPosition: 2,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 35 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_herbert_1",
    title: "Dűne",
    slug: "dune",
    description: "A sivatagbolygó, az Arrakis az univerzum legértékesebb anyagának, a fűszernek az egyetlen forrása.",
    authors: [{ name: "Frank Herbert" }],
    categories: [{ name: "Sci-Fi" }, { name: "Klasszikus" }],
    tags: [{ name: "arrakis" }, { name: "fűszer" }, { name: "paul atreides" }],
    averageRating: 4.9,
    ratingsCount: 2310,
    coverUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1965,
    pages: 620,
    seriesName: "Dűne",
    seriesPosition: 1,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_clarke_1",
    title: "2001. Űrodisszeia",
    slug: "2001-urodisszeia",
    description: "Egy rejtélyes fekete monolit felbukkanása a Holdon az emberiséget a Szaturnusz felé indítja.",
    authors: [{ name: "Arthur C. Clarke" }],
    categories: [{ name: "Sci-Fi" }, { name: "Filozófia" }],
    tags: [{ name: "hal 9000" }, { name: "monolit" }, { name: "űrutazás" }],
    averageRating: 4.6,
    ratingsCount: 980,
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1968,
    pages: 290,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_gibson_1",
    title: "Neurománc",
    slug: "neuromanc",
    description: "A kiberpunk irodalom alapműve: Case, a kiégett hacker egy utolsó nagy küldetésre kap megbízást.",
    authors: [{ name: "William Gibson" }],
    categories: [{ name: "Kiberpunk" }, { name: "Sci-Fi" }],
    tags: [{ name: "kibertér" }, { name: "ai" }, { name: "mátrix" }],
    averageRating: 4.5,
    ratingsCount: 840,
    coverUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1984,
    pages: 310,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_orwell_1",
    title: "1984",
    slug: "1984",
    description: "A Nagy Testvér mindent lát: George Orwell látnoki disztópiája az elnyomásról és a szabadságról.",
    authors: [{ name: "George Orwell" }],
    categories: [{ name: "Disztópia" }, { name: "Klasszikus" }],
    tags: [{ name: "nagy testvér" }, { name: "óceánia" }, { name: "totalitarizmus" }],
    averageRating: 4.9,
    ratingsCount: 3100,
    coverUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1949,
    pages: 328,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_orwell_2",
    title: "Állatfarm",
    slug: "allatfarm",
    description: "Minden állat egyenlő, de egyes állatok egyenlőbbek a többinél.",
    authors: [{ name: "George Orwell" }],
    categories: [{ name: "Szerepjáték" }, { name: "Klasszikus" }],
    tags: [{ name: "allegória" }, { name: "politika" }],
    averageRating: 4.7,
    ratingsCount: 1890,
    coverUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1945,
    pages: 140,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_bradbury_1",
    title: "Fahrenheit 451",
    slug: "fahrenheit-451",
    description: "Egy társadalom, ahol a könyvolvasás tiltott, és a tűzoltók feladata a könyvek elégetése.",
    authors: [{ name: "Ray Bradbury" }],
    categories: [{ name: "Disztópia" }, { name: "Sci-Fi" }],
    tags: [{ name: "könyvek" }, { name: "cenzúra" }],
    averageRating: 4.8,
    ratingsCount: 1650,
    coverUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1953,
    pages: 220,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_christie_1",
    title: "Gyilkosság az Orient expresszen",
    slug: "gyilkossag-az-orient-expresszen",
    description: "Hercule Poirot legendás vonatos nyomozása a hótorlaszban rekedt luxusvonaton.",
    authors: [{ name: "Agatha Christie" }],
    categories: [{ name: "Krimi" }, { name: "Klasszikus" }],
    tags: [{ name: "hercule poirot" }, { name: "orient expressz" }, { name: "rejtély" }],
    averageRating: 4.8,
    ratingsCount: 2200,
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1934,
    pages: 280,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_rejto_1",
    title: "A három testőr Afrikában",
    slug: "a-harom-testor-afrikaban",
    description: "Csülök, Senki Alfonz és Tuskó Hopkins felejthetetlen kalandjai a francia idegenlégióban.",
    authors: [{ name: "Rejto Jeno" }],
    categories: [{ name: "Humor" }, { name: "Kaland" }],
    tags: [{ name: "légió" }, { name: "csülök" }, { name: "magyar klasszikus" }],
    averageRating: 4.9,
    ratingsCount: 1950,
    coverUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1940,
    pages: 240,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_liu_1",
    title: "A háromtest-probléma",
    slug: "a-haromtest-problema",
    description: "Az emberiség első kapcsolata egy távoli idegen civilizációval a kulturális forradalom árnyékában.",
    authors: [{ name: "Liu Cixin" }],
    categories: [{ name: "Kemény Sci-Fi" }],
    tags: [{ name: "fizika" }, { name: "trisolaris" }],
    averageRating: 4.8,
    ratingsCount: 1750,
    coverUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=600&auto=format&fit=crop&q=80",
    publishedYear: 2008,
    pages: 410,
    distributionStatus: "LICENSED",
    libraryReleaseAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_verne_1",
    title: "Húszezer mérföld a tenger alatt",
    slug: "huszezer-merfold-a-tenger-alatt",
    description: "Nemo kapitány és a Nautilus lenyűgöző tenger alatti odisszeája.",
    authors: [{ name: "Jules Verne" }],
    categories: [{ name: "Kaland" }, { name: "Klasszikus" }],
    tags: [{ name: "nautilus" }, { name: "óceán" }],
    averageRating: 4.7,
    ratingsCount: 1320,
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1870,
    pages: 380,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
  },
];

export function getFallbackBookItems(): BookItem[] {
  return FALLBACK_BOOKS;
}
