import { BookItem } from "@librarian/ai";

export const FALLBACK_BOOKS: BookItem[] = [
  // ASIMOV FOUNDATION SERIES
  {
    id: "fb_asimov_1",
    title: "Alapítvány",
    slug: "alapitvany",
    description: "A Galaktikus Birodalom haldoklik. Hari Seldon pszichohistóriája alapján megalapítják az Alapítványt a galaxis peremén, hogy megőrizzék az emberiség tudását.",
    authors: [{ name: "Isaac Asimov" }],
    categories: [{ name: "Sci-Fi" }, { name: "Űropera" }, { name: "Klasszikus" }],
    tags: [{ name: "klasszikus" }, { name: "pszichohistória" }, { name: "hari seldon" }, { name: "birodalom" }],
    averageRating: 4.8,
    ratingsCount: 1420,
    coverUrl: "https://images.unsplash.com/photo-1618609377864-68609b857e90?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1951,
    pages: 255,
    seriesName: "Alapítvány",
    seriesPosition: 1,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_asimov_2",
    title: "Alapítvány és Birodalom",
    slug: "alapitvany-es-birodalom",
    description: "Az Alapítvány szembekerül a hajdani dicső Birodalommal és a titokzatos Öszvérrel, egy mutánssal, aki képes manipulálni az emberek érzelmeit.",
    authors: [{ name: "Isaac Asimov" }],
    categories: [{ name: "Sci-Fi" }, { name: "Űropera" }],
    tags: [{ name: "öszvér" }, { name: "galaxis" }, { name: "pszichológia" }],
    averageRating: 4.7,
    ratingsCount: 1120,
    coverUrl: "https://images.unsplash.com/photo-1532012164546-f432f2e3777f?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1952,
    pages: 247,
    seriesName: "Alapítvány",
    seriesPosition: 2,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 35 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_asimov_3",
    title: "Második Alapítvány",
    slug: "masodik-alapitvany",
    description: "Az Öszvér a Második Alapítvány nyomába ered, miközben az Első Alapítvány polgárai is fel akarják kutatni a titokzatos szellemi vezetőket.",
    authors: [{ name: "Isaac Asimov" }],
    categories: [{ name: "Sci-Fi" }, { name: "Űropera" }],
    tags: [{ name: "telepátia" }, { name: "galaxis" }, { name: "titok" }],
    averageRating: 4.8,
    ratingsCount: 990,
    coverUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1953,
    pages: 240,
    seriesName: "Alapítvány",
    seriesPosition: 3,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_asimov_4",
    title: "Az Alapítvány pereme",
    slug: "az-alapitvany-pereme",
    description: "Golan Trevize tanácsos kételkedni kezd a Seldon-tervben, és elindul, hogy felkutassa az emberiség elveszett bölcsőjét és a titokzatos Gaia bolygót.",
    authors: [{ name: "Isaac Asimov" }],
    categories: [{ name: "Sci-Fi" }, { name: "Űropera" }],
    tags: [{ name: "gaia" }, { name: "golan trevize" }, { name: "föld" }],
    averageRating: 4.6,
    ratingsCount: 850,
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1982,
    pages: 380,
    seriesName: "Alapítvány",
    seriesPosition: 4,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_asimov_5",
    title: "Alapítvány és Föld",
    slug: "alapitvany-es-fold",
    description: "Golan Trevize, Janov Pelorat és Bliss elérik az elfeledett Földet, ahol választ kapnak az emberi faj és a galaxis végső sorsának kérdéseire.",
    authors: [{ name: "Isaac Asimov" }],
    categories: [{ name: "Sci-Fi" }, { name: "Űropera" }],
    tags: [{ name: "föld" }, { name: "robotok" }, { name: "jövő" }],
    averageRating: 4.5,
    ratingsCount: 780,
    coverUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1986,
    pages: 410,
    seriesName: "Alapítvány",
    seriesPosition: 5,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 22 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_asimov_robot",
    title: "Én, a robot",
    slug: "en-a-robot",
    description: "A robotika három alaptörvénye és Susan Calvin robotpszichológus legendás esetei a gépek és emberek együttéléséről.",
    authors: [{ name: "Isaac Asimov" }],
    categories: [{ name: "Sci-Fi" }, { name: "Mesterséges Intelligencia" }],
    tags: [{ name: "robotok" }, { name: "alaptörvény" }, { name: "ai" }],
    averageRating: 4.8,
    ratingsCount: 1890,
    coverUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1950,
    pages: 250,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
  },

  // SCIENTIFIC & TECHNICAL MASTERPIECES
  {
    id: "fb_hidtervezes_1",
    title: "A hídtervezés elmélete és gyakorlata",
    slug: "a-hidtervezes-elmelete-es-gyakorlata",
    description: "Átfogó mérnöki kézikönyv függőhidak, gerendahidak, ívhidak tervezéséről, szerkezeti analíziséről, aerodinamikai stabilitásáról és modern alapozási technikáiról.",
    authors: [{ name: "Dr. Kovács Béla" }, { name: "Németh László" }],
    categories: [{ name: "Mérnöki tudományok" }, { name: "Építészet" }],
    tags: [{ name: "hídtervezés" }, { name: "statika" }, { name: "szerkezetépítés" }, { name: "aerodinamika" }],
    averageRating: 4.9,
    ratingsCount: 320,
    coverUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80",
    publishedYear: 2018,
    pages: 480,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_roma_1",
    title: "Róma tündöklése és bukása",
    slug: "roma-tundoklese-es-bukasa",
    description: "A Római Birodalom felemelkedésének, virágkorának és hanyatlásának monumentális történelmi krónikája és társadalmi elemzése.",
    authors: [{ name: "Edward Gibbon" }],
    categories: [{ name: "Történelem" }, { name: "Klasszikus" }],
    tags: [{ name: "róma" }, { name: "ókori történelem" }, { name: "császárság" }, { name: "légiók" }],
    averageRating: 4.8,
    ratingsCount: 890,
    coverUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&auto=format&fit=crop&q=80",
    publishedYear: 2015,
    pages: 650,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_kvantum_1",
    title: "Kvantummechanika alapjai",
    slug: "kvantummechanika-alapjai",
    description: "Világos és szemléletes bevezetés a kvantumelméletbe: hullám-részecske kettősség, Schrödinger-egyenlet, határozatlansági reláció és kvantum-összefonódás kevés felesleges matematikával.",
    authors: [{ name: "Szabó Miklós" }],
    categories: [{ name: "Fizika" }, { name: "Természettudomány" }],
    tags: [{ name: "kvantumfizika" }, { name: "schrödinger" }, { name: "részecskefizika" }, { name: "kvantummechanika" }],
    averageRating: 4.8,
    ratingsCount: 640,
    coverUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80",
    publishedYear: 2020,
    pages: 310,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },

  // SCI-FI & FANTASY ICONS
  {
    id: "fb_herbert_1",
    title: "Dűne",
    slug: "dune",
    description: "A sivatagbolygó, az Arrakis az univerzum legértékesebb anyagának, a fűszernek az egyetlen forrása. Paul Atreides epikus utazása a prófétasághoz.",
    authors: [{ name: "Frank Herbert" }],
    categories: [{ name: "Sci-Fi" }, { name: "Klasszikus" }],
    tags: [{ name: "arrakis" }, { name: "fűszer" }, { name: "paul atreides" }, { name: "sivatag" }],
    averageRating: 4.9,
    ratingsCount: 2310,
    coverUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1965,
    pages: 620,
    seriesName: "Dűne",
    seriesPosition: 1,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_clarke_1",
    title: "2001. Űrodisszeia",
    slug: "2001-urodisszeia",
    description: "Egy rejtélyes fekete monolit felbukkanása a Holdon az emberiséget a Szaturnusz felé indítja a HAL 9000 szuperszámítógép kíséretében.",
    authors: [{ name: "Arthur C. Clarke" }],
    categories: [{ name: "Sci-Fi" }, { name: "Filozófia" }],
    tags: [{ name: "hal 9000" }, { name: "monolit" }, { name: "űrutazás" }, { name: "mesterséges intelligencia" }],
    averageRating: 4.6,
    ratingsCount: 980,
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1968,
    pages: 290,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_gibson_1",
    title: "Neurománc",
    slug: "neuromanc",
    description: "A kiberpunk irodalom alapműve: Case, a kiégett hacker egy utolsó nagy küldetésre kap megbízást a neurális mátrix legsötétebb bugyrain át.",
    authors: [{ name: "William Gibson" }],
    categories: [{ name: "Kiberpunk" }, { name: "Sci-Fi" }],
    tags: [{ name: "kibertér" }, { name: "ai" }, { name: "mátrix" }, { name: "hacker" }],
    averageRating: 4.5,
    ratingsCount: 840,
    coverUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1984,
    pages: 310,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_lem_1",
    title: "Solaris",
    slug: "solaris",
    description: "Kris Kelvin pszichológus megérkezik a távoli Solaris kutatóállomásra, ahol a felszínt borító élő óceán az emberek legmélyebb bűntudatát formálja testté.",
    authors: [{ name: "Stanislaw Lem" }],
    categories: [{ name: "Sci-Fi" }, { name: "Filozófia" }],
    tags: [{ name: "idegen intelligencia" }, { name: "óceán" }, { name: "pszichológia" }],
    averageRating: 4.7,
    ratingsCount: 1100,
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1961,
    pages: 230,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 35 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_liu_1",
    title: "A háromtest-probléma",
    slug: "a-haromtest-problema",
    description: "Az emberiség első kapcsolata egy távoli, instabil csillagrendszerben élő idegen civilizációval a kulturális forradalom árnyékában.",
    authors: [{ name: "Liu Cixin" }],
    categories: [{ name: "Hard Sci-Fi" }, { name: "Sci-Fi" }],
    tags: [{ name: "fizika" }, { name: "trisolaris" }, { name: "idegen civilizáció" }],
    averageRating: 4.8,
    ratingsCount: 1750,
    coverUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=600&auto=format&fit=crop&q=80",
    publishedYear: 2008,
    pages: 410,
    distributionStatus: "LICENSED",
    libraryReleaseAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },

  // DYSTOPIAS & PHILOSOPHY
  {
    id: "fb_orwell_1",
    title: "1984",
    slug: "1984",
    description: "A Nagy Testvér mindent lát: George Orwell látnoki disztópiája az elnyomásról, az újbeszélről és a gondolatrendőrségről.",
    authors: [{ name: "George Orwell" }],
    categories: [{ name: "Disztópia" }, { name: "Klasszikus" }],
    tags: [{ name: "nagy testvér" }, { name: "óceánia" }, { name: "totalitarizmus" }],
    averageRating: 4.9,
    ratingsCount: 3100,
    coverUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1949,
    pages: 328,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_orwell_2",
    title: "Állatfarm",
    slug: "allatfarm",
    description: "Minden állat egyenlő, de egyes állatok egyenlőbbek a többinél. George Orwell halhatatlan politikai szatírája.",
    authors: [{ name: "George Orwell" }],
    categories: [{ name: "Filozófia" }, { name: "Klasszikus" }],
    tags: [{ name: "allegória" }, { name: "politika" }, { name: "szatíra" }],
    averageRating: 4.7,
    ratingsCount: 1890,
    coverUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1945,
    pages: 140,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_bradbury_1",
    title: "Fahrenheit 451",
    slug: "fahrenheit-451",
    description: "Egy társadalom, ahol a könyvolvasás tiltott bűncselekmény, és a tűzoltók feladata a megtalált könyvek elégetése.",
    authors: [{ name: "Ray Bradbury" }],
    categories: [{ name: "Disztópia" }, { name: "Sci-Fi" }],
    tags: [{ name: "könyvek" }, { name: "cenzúra" }, { name: "tűzoltók" }],
    averageRating: 4.8,
    ratingsCount: 1650,
    coverUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1953,
    pages: 220,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
  },

  // CRIME & ADVENTURE
  {
    id: "fb_christie_1",
    title: "Gyilkosság az Orient expresszen",
    slug: "gyilkossag-az-orient-expresszen",
    description: "Hercule Poirot legendás vonatos nyomozása a balkáni hótorlaszban rekedt luxusvonaton lezajlott rejtélyes bűntény ügyében.",
    authors: [{ name: "Agatha Christie" }],
    categories: [{ name: "Krimi" }, { name: "Klasszikus" }],
    tags: [{ name: "hercule poirot" }, { name: "orient expressz" }, { name: "rejtély" }],
    averageRating: 4.8,
    ratingsCount: 2200,
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1934,
    pages: 280,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_rejto_1",
    title: "A három testőr Afrikában",
    slug: "a-harom-testor-afrikaban",
    description: "Csülök, Senki Alfonz és Tuskó Hopkins felejthetetlen, kacagtató kalandjai a francia idegenlégióban.",
    authors: [{ name: "Rejto Jeno" }],
    categories: [{ name: "Humor" }, { name: "Kaland" }],
    tags: [{ name: "légió" }, { name: "csülök" }, { name: "magyar klasszikus" }],
    averageRating: 4.9,
    ratingsCount: 1950,
    coverUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1940,
    pages: 240,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_rejto_2",
    title: "Piszkos Fred, a kapitány",
    slug: "piszkos-fred-a-kapitany",
    description: "A tenger fenegyereke és Fülig Jimmy hajónaplójának zseniális bonyodalmai Szingapúrtól a déltengerekig.",
    authors: [{ name: "Rejto Jeno" }],
    categories: [{ name: "Humor" }, { name: "Kaland" }],
    tags: [{ name: "piszkos fred" }, { name: "fülig jimmy" }, { name: "tenger" }],
    averageRating: 4.9,
    ratingsCount: 2100,
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1940,
    pages: 260,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "fb_verne_1",
    title: "Húszezer mérföld a tenger alatt",
    slug: "huszezer-merfold-a-tenger-alatt",
    description: "Nemo kapitány és a legendás Nautilus tengeralattjáró lenyűgöző világkörüli tenger alatti expedíciója.",
    authors: [{ name: "Jules Verne" }],
    categories: [{ name: "Kaland" }, { name: "Klasszikus" }],
    tags: [{ name: "nautilus" }, { name: "óceán" }, { name: "nemo kapitány" }],
    averageRating: 4.7,
    ratingsCount: 1320,
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    publishedYear: 1870,
    pages: 380,
    distributionStatus: "PUBLIC_DOMAIN",
    libraryReleaseAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
  },
];

export function getFallbackBookItems(): BookItem[] {
  return FALLBACK_BOOKS;
}
